# Generated by Django 5.1.2 on 2024-10-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('colors', models.JSONField()),
                ('title_font', models.CharField(max_length=255)),
                ('subtitle_font', models.CharField(max_length=255)),
                ('body_font', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('demographic', models.CharField(max_length=255)),
                ('psychographic', models.CharField(max_length=255)),
                ('audience_interest', models.CharField(max_length=255)),
                ('tone_of_voice', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('playful', 'Playful'), ('authoritative', 'Authoritative')], max_length=20)),
                ('message_style', models.CharField(choices=[('inspire', 'Inspire'), ('educate', 'Educate'), ('promote', 'Promote'), ('humour', 'Humour')], max_length=20)),
                ('visual_style', models.CharField(choices=[('minimalistic', 'Minimalistic'), ('bold', 'Bold'), ('vibrant', 'Vibrant'), ('professional', 'Professional')], max_length=20)),
                ('keywords', models.JSONField()),
                ('cta_required', models.BooleanField()),
                ('cta_text', models.CharField(max_length=255)),
                ('current_campaign', models.CharField(max_length=255)),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('mood', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(max_length=255)),
                ('advanced', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
