# Generated by Django 5.1.2 on 2024-10-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandcreation',
            name='cta_required',
        ),
        migrations.AddField(
            model_name='brandcreation',
            name='template',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brandcreation',
            name='message_style',
            field=models.CharField(choices=[('inspire', 'Inspire'), ('educate', 'Educate'), ('promote', 'Promote')], max_length=20),
        ),
        migrations.AlterField(
            model_name='brandcreation',
            name='visual_style',
            field=models.CharField(choices=[('minimalistic', 'Minimalistic'), ('bold', 'Bold'), ('vibrant', 'Vibrant')], max_length=20),
        ),
    ]
